### ISSUE TITLE
Cannot load official manifest MoM for version 18520

### ISSUE THREAD

**Issue by introllo** [clearlinux/docker-brew-clearlinux#1]
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM clearlinux:base
 ---> 34d5e7cc93b7
Step 2/2 : RUN swupd bundle-add editors dev-utils
 ---> Running in 60327fe3112f
swupd-client bundle adder 3.12.5
   Copyright (C) 2012-2017 Intel Corporation

ERROR: 35
Failed to retrieve 18520 MoM manifest
Cannot load official manifest MoM for version 18520
The command '/bin/sh -c swupd bundle-add editors dev-utils' returned a non-zero code: 4

I am behind a proxy when I run this and have passed in proxy info via build-args.

Suggestions?

$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by bryteise** [comment]
Ah this is a problem with the base image. If you want to get around this in the meantime please run clrtrust generate (it populates the keystore with the system certificates).

**Comment by introllo** [comment]
That works. Thanks for quick response.

I did get a warning for systemctl. Not fatal though. 

Calling post-update helper scripts.
WARNING: systemctl not operable, unable to run systemd update triggers
Bundle(s) installation done.

**Comment by bryteise** [comment]
@introllo Does adding --no-boot-update to swupd update make that go away?

**Comment by introllo** [comment]
No change. Here is my Dockerfile...

FROM clearlinux:base
RUN clrtrust generate
RUN swupd bundle-add --no-boot-update editors dev-utils

**Comment by bryteise** [comment]
Ah sorry I was mistaken, that warning is intentional until we get some fall back in place for running the update triggers outside of systemd for Docker.

**Comment by introllo** [comment]
No worries. Awesome work. Will track it closely.
